go.mod
go.sum
internal/discord/command-handlers.go
internal/discord/commands.go
internal/discord/discord.go
internal/discord/handlers.go
main.go

This PR creates the base Moddingway bot and registers the basic moderation commands on Discord, which are only dummy functions at this point.

Create Moddingway base

---

internal/discord/command-handlers.go
internal/discord/commands.go

Added slash commands to warn, clear warnings, delete a warning, and show all warnings for a user, with necessary options and descriptions. Integrated handling of these commands in the InteractionCreate function.

Add warning commands

---

internal/discord/command-handlers.go
internal/discord/commands.go
internal/discord/const.go
internal/discord/discord.go

`mapOptions` creates a map from arguments given in the slash command used.
`ContinueInteraction` sends a follow-up interaction to the user after the initial interaction.
`CheckUserInGuild` checks if the user is in the specified server.

Add function helpers for slash commands

---

internal/discord/command-handlers.go

This commit changes the exile duration to optional.

Update command options for Exile and Unexile commands

---

docker-compose.yml
docker/Postgres.Dockerfile
postgres/create_tables.sql
postgres/seed_data.sql

Create local postgres instance via Docker for local development. Create users and strikes tables in DB init file

Create Postgres in docker and initialize tables

---

.gitignore
docker-compose.yml
docker/App.Dockerfile

`docker-compose.yml` will check a local file named `.env` for the `DISCORD_TOKEN` (and other secrets if needed in the future)

Add dockerfile for moddingway app

---

internal/discord/commands.go

Allow SetModLoggingChannel to send embed logs.

---

internal/discord/command-handlers.go
internal/discord/const.go
internal/discord/discord.go

Dependent on #28 
Resolves #21 
Default specified guild is set to NAUR
Leaving this as draft until #28 is merged to prevent messy commits

Limit creation of commands to a single specified guild

---

internal/discord/command-handlers.go
internal/discord/commands.go

Fixed the Issue #84 . This PR removes the following commands and code stubs:
- /slowmode
- /slowmodeoff
- /kick

Removed the unneeded Commands. Fixes #84

---

internal/discord/command-handlers.go
internal/discord/commands.go
main.go

Remove OS write logging output, only output to stdout

remove file write for logging

---

internal/discord/command-handlers.go
internal/discord/commands.go

Mute, Unmute, RemoveNickname, SetNickname, Purge, and setmodloggingchannel commands were removed as they are no longer needed in the application.

Decommision unnused commands

---

internal/database/strikes.go
internal/discord/commands.go
postgres/create_tables.sql

Add strikes DB table, create methods to interact with table, add strikes command (still hidden)

add methods to interact with strikes db

---

.gitignore
README-python.md
src/bot.py
src/commands/exile.py
src/commands/exile_commands.py
src/commands/helper.py
src/enums.py
src/main.py
src/services/exile_service.py
src/settings.py
src/util.py

Initial python rewrite skeleton. Extra work that needs to get done is listed in main.py

Python initial code

---

src/commands/ban_commands.py
src/commands/exile_commands.py
src/commands/helper.py

Creates a context manager for the interaction response. Initially sends an interim message and edits the interim message accordingly upon return.
Currently set message is "Processing..."

Respond with interim message when command is initially received.

---

.github/workflows/commit-check.yaml

ci: Add workflow to check for ticket number in PR descriptions

---

src/bot.py
src/commands/exile_commands.py
src/commands/helper.py

Also remove some logs placed during outage debugging

Show exile duration formatting in command prompt

---

src/commands/exile_commands.py

Make Roulette safe 5 times out of 6, and then make it always pick a duration if you fail
Ticket: MOD-18

make roulette safe 5/6 times

---

.github/workflows/commit-check.yaml
src/util.py
src/workers/forum_automod.py
src/workers/helper.py

Ticket: MOD-27
[MOD-27]: https://naurffxiv.atlassian.net/browse/MOD-27?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Automod archived threads

---

src/commands/exile_commands.py
src/util.py

Update the formatting for exile duration to the form of (1-99)(day/min/sec/hour)
Ticket: MOD-13

Update exile string formatting

---

README.md
src/settings.py
src/util.py
src/workers/forum_automod.py
src/workers/helper.py

Ticket: MOD-47
This PR updates Moddingway to notify the user of their thread being automodded in the specified channel (#bot-channel)

Notify user of thread deletion through channel message

---

src/commands/exile_commands.py

Prevent exile from logging if user survived roulette

---

Makefile

Add black formatting to MakeFile

---

src/commands/exile_commands.py

Use correct string type for roulette exile
Ticket: MOD-54

fix roulette exile duration

---

requirements.txt
src/database/exiles_database.py
src/services/exile_service.py

Fix list exiles to show more than 1 exile, simplify list exile formatting to be more friendly for mobile
Ticket: MOD-54

Mod 54 fix logging

---

src/commands/exile_commands.py
src/database/exiles_database.py
src/enums.py
src/services/exile_service.py

Ticket: MOD-7
Decommission INDEFINITE EXILES.

Change exile duration to required

---

src/services/exile_service.py

Ticket: MOD-79
Adds a discord timestamp for time remaining as well as some formatting updates.

Update exile to add remaining time

---

src/services/exile_service.py

Ticket: MOD-77
User will now be DM'd when an exile expires

DM user when un-exiled

---

postgres/create_tables.sql

permanent version of strikes DB changes
Ticket: MOD-26

permanent version of strikes changes

---

.github/workflows/tagging.yaml

Tag commits for 1.0.2

---

.github/workflows/tagging.yaml

Tag commits for 1.1.0

---

src/bot.py
src/commands/slowmode_commands.py
src/services/slowmode_service.py

Ticket: MOD-53
- Adds the slash slowmode command
- Allows user to enter 0 (off) to 21600 (6hours) seconds for a slowmode interval
- Includes potential error handling and checks if channel is already set to the desired interval

Implement Slowmode Command

---

.github/workflows/tagging.yaml

Fix tagging

---

Makefile
postgres/create_tables.sql
postgres/drop_all_tables.sql
postgres/seed_data.sql

Add clean DB command

---

postgres/create_tables.sql
requirements.txt
src/bot.py
src/commands/strikes_command.py
src/database/models/__init__.py
src/database/models/user.py
src/database/users_database.py
src/enums.py
src/main.py
src/services/exile_service.py
src/services/strike_service.py

change user model to have validation on it via pydantic, to help with typing
Ticket: MOD-20

Clean up user model

---

src/commands/strikes_command.py
src/database/strikes_database.py
src/services/strike_service.py

Ticket: MOD-18
List strikes and points for a user

list strikes command

---

src/commands/slowmode_commands.py
src/commands/strikes_command.py

Ticket: NA
fix slowmode, defaults to channel of interaction.

Default slowmode channel to interaction channel

---

src/commands/helper.py
src/database/connection.py
src/database/models/strike.py
src/database/models/user.py
src/main.py
src/services/strike_service.py

Exile validation fix

---

src/commands/exile_commands.py
src/services/exile_service.py

Ticket: MOD-115
- Change command to be normalized with others.
- Normalize other key user facing details
- Update user facing details to be present tense instead of future tense.

Update user facing exile details

---

src/commands/exile_commands.py
src/commands/helper.py
src/services/exile_service.py

Ticket: MOD-82
The /exile and /roulette log embed now have expiration field showing dynamic timestamp.They also have nicer text in the duration field.

Update durations to be in Epoch Unix Timestamp and more

---

src/services/ban_service.py
src/services/exile_service.py
src/services/slowmode_service.py
src/services/strike_service.py
src/util.py

Ticket: MOD-111
Ticket: MOD-97
Ticket: MOD-112
Ticket: MOD-113
Ticket: MOD-42

Update embeds to be uniform

---

src/settings.py
src/workers/forum_automod.py

Ticket: MOD-118
Also un-comment FRU channels

Update Auto Mod Recruitment Message

---

postgres/create_tables.sql
postgres/drop_all_tables.sql
postgres/seed_data.sql

Ticket:MOD-23
Added required queries for notes table.

Add notes table to db

---

moddingway/commands/strikes_command.py

Fix formatting

---

.github/workflows/python-unittest.yml
tests/pytest.ini
tests/unit/conftest.py
tests/unit/test_util.py

Test utils method with Discord mocks

---

moddingway/bot.py
moddingway/commands/note_commands.py
moddingway/database/models/__init__.py
moddingway/database/models/note.py
moddingway/database/notes_database.py
moddingway/services/note_service.py
moddingway/services/strike_service.py
postgres/create_tables.sql
postgres/drop_all_tables.sql
postgres/seed_data.sql

Ticket:MOD-2
Ticket:MOD-17
Ticket:MOD-33
Ticket:MOD-22
Ticket:MOD-19
Ticket:MOD-23

Note System 

---

src/constants.py
src/services/strike_service.py

Ticket:MOD-137
Cumulative punishment when crossing multiple thresholds at once
Non-cumulative punishment when staying between thresholds after getting a strike

Change the strike punishment threshold to include the previous punishment if not passed

---

tests/unit/conftest.py
tests/unit/services/test_exile_service.py
tests/unit/test_util.py

Initial exile service tests

---

moddingway/services/strike_service.py

Changed a field title in strike service from Result to Strike Points 

---

moddingway/commands/helper.py
moddingway/workers/forum_automod.py
moddingway/workers/helper.py

Ticket: NA
Adds stack trace info to general error handlers

Add stack trace info to general error handlers

---

moddingway/database/users_database.py
moddingway/workers/__init__.py
moddingway/workers/strike_decrement.py

Have users who have no strikes for the last 90 days lose 1 temporary point
Ticket: MOD-24

Implement strike decay

---

moddingway/util.py

mark regex as appropriate string

---

moddingway/commands/note_commands.py
moddingway/services/note_service.py

Allow add_note on non-members

---

moddingway/commands/strikes_command.py

Fix missing add_strike description
Ticket: NA

fix missing add strike description

---

moddingway/commands/exile_commands.py
moddingway/database/exiles_database.py
moddingway/services/exile_service.py

Ticket:MOD-83
Command that deletes non active(past) exiles with exile_id

Implement /delete_exile command

---

moddingway/database/connection.py

Ticket: MOD-141
check if the DB connection is closed, reconnect if it is

reopen connection if closed

---

tests/unit/services/test_strike_service.py

test updated according to ban command functionality change

---

postgres/create_tables.sql

Convert indefinite exiles to be exiles of 1 year
Ticket: MOD-109

update indefinite exiles to timed

---

postgres/create_tables.sql

Fix syntax issue with create tables script
Ticket: NA

fix syntax in create tables script

---

moddingway/commands/strikes_command.py
moddingway/database/strikes_database.py
moddingway/database/users_database.py
moddingway/services/strike_service.py

Add command to remove strike `/delete_strike`
Ticket: MOD-16

Delete strike by ID

---

moddingway/commands/exile_commands.py

remove double expiration field on roulette exile

---

moddingway/services/strike_service.py

fix apply strike peanalty

---

moddingway/database/exiles_database.py

show roullette exiles in view active

---

moddingway/commands/exile_commands.py

This commit allows for users to opt out of roulette if they don't know what
they're getting themselves into.
Ticket: MOD-156

Add UI for roulette command

---

moddingway/commands/helper.py

quick fix for roulette bug

---

moddingway/commands/helper.py

handle second piece of bug

---

moddingway/bot.py
moddingway/events/member_events.py

Instead of making the bot a singleton, pass it to the register events in the same way we register regular commands
https://github.com/naurffxiv/moddingway/issues/260

Register events alongside bot

---

moddingway/database/models/user.py
moddingway/database/users_database.py
moddingway/events/member_events.py
postgres/create_tables.sql
tests/unit/services/test_exile_service.py

Ticket: MOD-269
Add DB update to create isBanned column, with default of false
add event handlers for user being banned or unbanned

Add event handler for member ban

---

moddingway_api/routes/banneduser_routes.py

Implement unban endpoint

---

postgres/create_tables.sql
postgres/drop_all_tables.sql

Drop roles table in cleanup script to allow users to drop properly
Add isBanned  to create users table to make schema more clear

Clean up sql seed and reseed scripts

---

postgres/create_tables.sql
postgres/drop_all_tables.sql

add forms DB schema

---

moddingway/commands/exile_commands.py

Ticket: None 
roulette command disabled preparing to take down the bot temporarily because bot will not be online to unexile people

disable roulette command

---

moddingway/commands/exile_commands.py

enable roulette command

---

moddingway/bot.py
moddingway/commands/warning_commands.py
moddingway/database/models/note.py
moddingway/database/notes_database.py
moddingway/services/note_service.py
postgres/create_tables.sql

updated create_tables sql script <- needs review for update script
commented out old update script for userRoles
notesdb has isWarning column
/warn command
/view_warnings command
/view_notes now shows if a note was a warning
Closes: #258

warn command

---

.github/ISSUE_TEMPLATE/bug-report.md

This commit updates the issue reporting bug template. The template now
includes observed behavior to help with debugging.

Update bug template

---

moddingway/constants.py

remove sticky roles

---

moddingway/constants.py

This reverts commit 47bfa9558d1601b02529db278cbe98cb57bc0d90.

Revert "remove sticky roles (#339)"

---

main.py
moddingway/workers/autounexile.py
moddingway/workers/forum_automod.py
moddingway/workers/strike_decrement.py

Added worker startup logging and updated log format with timestamps.

Added worker startup logging and added worker keywords to log output

---

.github/workflows/publish.yaml
.github/workflows/python-unittest.yml
.github/workflows/pythonci-format-check.yml

This commit also updates the python versions to 3.13

Update workflows to run on dev
