naurffxiv/moddingway

internal/discord/command-handlers.go, internal/discord/discord.go, main.go
This PR creates a map of existing roles on bot initialization. It also adds a wait before bot is fully initialized.
Map is structured like so: `Roles[guild_id][role_name]` where the value is a `*discordgo.Role`.
=> Get guild roles on initialization

docker-compose.yml, main.go
Part of #50 
Dependent on #27 and #29
Adds a way to easily override the default guild ID and log channel ID set in `const.go` through environment variables to test the bot on a personal server without having to change it every time.
To use, set `DEBUG` to true in `.env` and the corresponding `GUILD_ID` and `MOD_LOGGING_CHANNEL_ID`
Leaving this as draft until #27 and #29 is merged to prevent messy commits (will be redone when they are merged)
=> Make testing the bot easier

.gitignore, internal/discord/command-handlers.go, internal/discord/commands.go, internal/discord/discord.go
This PR fixes all current linter issues. It also makes a minor change to the ban command, only responding with a success after the ban is actually performed and adding an error check if it fails.
During refactoring, I'll be moving the error checking for `SendDMToUser()` to the caller, so I opted to keep the return value and use a blank identifier for the return values for now (since it currently handles errors).
=> Fix all current linter issues and minor ban command change

internal/util/env-getter.go, main.go
Currently for every environment variable we get, we need to error check like so:
```golang
discordToken, ok := os.LookupEnv("DISCORD_TOKEN")
if !ok {
panic("You must supply a DISCORD_TOKEN to start!")
}
guildID, ok := os.LookupEnv("GUILD_ID")
if !ok {
panic("You must supply a GUILD_ID to start!")
}
modLoggingChannelID, ok := os.LookupEnv("MOD_LOGGING_CHANNEL_ID")
if !ok {
panic("You must supply a MOD_LOGGING_CHANNEL_ID to start!")
}
// rest of the env vars
```
This helper will allow us to simplify it slightly and move error checking to right before we start any connections.
```golang
discordToken := eg.GetEnv("DISCORD_TOKEN")
guildID := eg.GetEnv("GUILD_ID")
modLoggingChannelID := eg.GetEnv("MOD_LOGGING_CHANNEL_ID")
// rest of the env vars
if !eg.Ok {
tempstr := fmt.Sprintf("You must …
```
=> Make getting environment variables cleaner

Makefile, postgres.override.yml, postgres.yml
This PR adds another docker compose file that overrides the main `docker-compose.yml` with additional parameters to create and point to a postgres database in the same container.
To use run `make test-build` or `docker compose -f postgres.yml up --build`.
=> Add postgres service as an option for testing

internal/discord/command-handlers.go
Log the message that is added to logging channel to the honeycomb / stdout logs
=> log message being appended to discord log

internal/discord/temp.go, internal/discord/util.go, internal/worker/autounexile.go
Resolves #95 
Since I was here, I also deferred removing the DB entry to ensure the exile entry will get removed from the database even on errors. This will ensure that we don't try to unexile again the next time around if the exile somehow fails.
=> Add DMing user back to auto-unexile

src/commands/exile_commands.py, src/enums.py, src/services/exile_service.py, src/util.py
I suspect this function will be used throughout a lot more files when we add more commands, so it's better to move it out preemptively
=> Move is_user_moderator to util.py

src/commands/ban_commands.py, src/commands/exile_commands.py, src/commands/helper.py, src/database/exiles_database.py, src/services/exile_service.py, src/util.py
Adds a base function to create embeds for reusability. Updates the existing `create_logging_embed()` to use the function and adds command parameters to the embed. Additionally sets the footer to the relevant exile ID in applicable functions.
Base function will be reused with auto unexile
=> Create reusable embed function

Makefile
This commit adds the build flag to `docker compose up` to ensure that new code changes will always be included in the docker build. Without this flag, the new code will not be compiled into the build properly.
=> Add build flag to docker compose up

internal/discord/commands.go, src/services/ban_service.py
The ban appeal process needs updated now and in the future. The dyno link no longer works so the user will need to contact one of the staff to start the appeal process.
Once the site is able to begin the appeal, process, this will need to be updated again.
=> Update ban appeal DM

requirements.txt, src/commands/exile_commands.py, src/commands/helper.py, src/database/exiles_database.py, src/services/exile_service.py
* Create command to show user's exiles
* When parsing duration fails on exile command, clearly state that the user will not be exiled
* Do not create log when parsing exile duration fails
* Try/catch around sending user DMs, since failures are expected when user blocks DMs
Screenshot is taken on a 1080p monitor with both discord sidebars open, not sure if there's a better way to handle long reason messages. Lorem ipsum example is 508 characters long
Ticket: MWAY-13 MWAY-4
=> Create a command to show user exiles

README.md, src/settings.py, src/workers/__init__.py, src/workers/forum_automod.py, src/workers/helper.py
Ticket: [MWAY-15](https://naurffxiv.atlassian.net/browse/MWAY-15)
Adds a task that runs once every 24 hours that checks threads for activity requirements. Additionally, the task also checks if the starter message is present. If the thread doesn't meet either requirements, it's deleted and a DM will be sent (commented out for now to deal with backlog present in NAUR) to the original owner. A log will also be made upon each deletion.
In debug mode, it will check for the `INACTIVE_FORUM_CHANNEL_ID` and `INACTIVE_FORUM_DURATION` environment variables.
[MWAY-15]: https://naurffxiv.atlassian.net/browse/MWAY-15?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Delete threads that do not meet activity requirements

src/workers/forum_automod.py, src/workers/helper.py
Condenses automod logs from a per-thread basis to a per-forum channel basis.
First embed: Failed DM, per person (on failed DM)
Second embed: Total stats, per forum channel
=> Condense automod logs

src/commands/ban_commands.py, src/database/exiles_database.py, src/database/models/pending_exile.py, src/enums.py, src/services/exile_service.py, src/workers/autounexile.py, src/workers/helper.py
Ticket: MOD-14
This PR fixes a bug where autounexile did not remove exile entries upon failure and now additionally properly handles cases where the user left during the timed exile. It also fixes a minor typo in the ban command.
[MWAY-26]: https://naurffxiv.atlassian.net/browse/MWAY-26?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix autounexile looping on fail

.github/workflows/commit-check.yaml
Ticket: NA
Updates the check to process each line as a separate string so the literal `\r\n` in which the PR is received doesn't matter.
Also now accepts either `Ticket`, `TICKET`, or `ticket`
=> Fix PR ticket check

.github/workflows/tagging.yml
As we want to see what goes into each release, we should label each commit with a tag to make finding out the release content easier.
Ticket: MOD-51
=> Tag commits

src/commands/helper.py
Ticket: MOD-76
Current timestamp is retrieved along with the amount of seconds left on cooldown. The output adds both values together to get the unix timestamp for the end of the cooldown period. The same line of code formats the message into the markdown format discord allows showing how much time is remaining regardless of days, hours, or seconds.
Reference for unix timestamp discord capability: https://gist.github.com/LeviSnoot/d9147767abeef2f770e9ddcd91eb85aa
=> Update timestamp for cooldown period

postgres/create_tables.sql
Since we are currently set up to do all DB changes at once, but strikes table is in a less-than-ideal spot (old changes mean bad columns etc) I am making this intermediary PR to remove the old strikes table, create from scratch the corrected strikes table, and update the users table to have the new columns it needs. I will make a follow up once this change is deployed to not have subsequent deployments cause issues
Ticket: MOD-87
=> Add Strikes table and strikes user columns

src/util.py, src/workers/forum_automod.py, src/workers/helper.py
Ticket: MOD-86
This PR condenses the automod notification message into a bulk ping. 
`send_chunked_message()` has been added to `util.py` that automatically splits messages that may exceed discord's character limit. `chunk_generator()` may also be used to extend functionality to embeds (3k characters max) if needed. I also fixed a small bug with error logging + made an error slightly more verbose
=> Add chunked message helper function and condense automod notification message

src/commands/helper.py, src/enums.py, src/services/exile_service.py, src/util.py
Ticket: MOD-28
- Removes all unnecessary is_user_moderator roles and checks only if the user has "Mod" role.
- Better error handeling if the role is missing in is_user_moderator check
- `ERROR:commands.helper:An unexpected error has occurred The check functions for command` will no longer be reported if check is failed, gracefully catching this error
=> More robust role checks

src/services/exile_service.py
Ticket: MOD-81
Bot returns an error if target trying to get unexiled does not exist in database.
Note: I am not sure if there is a condition where user exists in users table but not in the exiles so I could not get the next if statement to trigger. Please review.
=> Take out excessive user in db check for unexile

README.md, src/commands/ban_commands.py, src/commands/helper.py, src/services/ban_service.py, src/ui/__init__.py, src/ui/ban_modal.py, src/ui/exile_modal.py, src/ui/helper.py
Ticket: MOD-89
- Users cannot ban someone with equal or higher role their current role via moddingway.
- User is given the error when trying to ban someone of equal or higher rank: Unable to ban {user.mention}: You cannot ban a user with an equal or higher role than yourself
- Fixed README to be up to date with current scope of role requirements
=> Fix ban command so staff cannot ban each other

src/commands/exile_commands.py, src/services/exile_service.py
Ticket:MOD-95
get_user_exiles now doesnt send an embed to log channel unless there is error
removed embed param from the function
=> Stop the view_exiles command from logging an embed UNLESS it fails

src/commands/exile_commands.py, src/enums.py, src/services/exile_service.py
Ticket: MOD-90
/exile and /roulette(when succesfull) now errors out when they target a mod
=> Stop exile command from being used on Mods and Admins

src/commands/strikes_command.py, src/services/strike_service.py
strike related functions now use interaction param when calling the exile_user() function
=> bug fix for mod-90

src/services/strike_service.py
Ticket: MOD-124
Strike threshold calculation is now done cumulatively instead of just highest tier taking over
fixed bug with perma ban triggered by strikes using ban_user func correctly
=> Strike threshold calculation is now done cumulatively

moddingway/util.py, tests/unit/test_util.py
Add a few simple tests for utils method. Fixed a bug with the message split method when a break happened exactly on a word, and trimmed the output
Ticket: NA
=> add tests for simple util methods

src/commands/ban_commands.py, src/commands/exile_commands.py, src/commands/strikes_command.py, src/services/exile_service.py, src/services/strike_service.py
Ticket:MOD-90
ban command checks if target is a mod outside of context manager
exile command now checks if target is a mod instead of comparing top roles
when a mods roulette command goes through it mimicks a users version but doesnt do anything in the backend
removed interaction param from exile_user function as its not needed anymore 
add strike command now checks if target user has mod role
=> moderation commands now checks if target has the mod role

moddingway/commands/exile_commands.py, moddingway/commands/note_commands.py, moddingway/commands/strikes_command.py, moddingway/services/note_service.py, moddingway/services/strike_service.py
Ticket: MOD-139
This allows moderators to use `/view_strikes` on any user not in the server with their discord id.
=> Allow view strikes on non-members

Makefile, README.md, moddingway_api/main.py, moddingway_api/routes/__init__.py, moddingway_api/routes/user_routes.py, moddingway_api/schemas/user_schema.py, requirements-api.txt, requirements.txt
Create initial fastAPI boilerplate with an example endpoint
ticket: MOD-66
=> Initial fastAPI setup with example endpoint

moddingway/constants.py
Ticket: MOD-149
These are extra roles that should be removed from users when they are exiled. Right now there are no current roles the need to be removed other than verified. Verified is already covered in the main exile method.
=> Remove STICKY_ROLES from constants

moddingway/util.py, moddingway/workers/forum_automod.py, moddingway/workers/helper.py
[Refactored get_log_channel to use self instead of guild, updated calls](https://github.com/naurffxiv/moddingway/commit/04062ac86a72f3861484efb249e7a23641195e4d)
Refactored get_log_channel function to reference self instead of guild to resolve ModdingwayBot guild attribute reference exception. Updated usages in helper.py. Resolves Issue https://github.com/naurffxiv/moddingway/issues/334.
=> Auto-unexile should work, Worker should clean up inactive forums

moddingway/events/member_events.py, moddingway/util.py
Reverted #353, as function is only accessing cached data.
Fixes broken manual automod command and on member join events.
=> Reverted async definition of get_log_channel
